import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconStethoscope,
  IconDeviceHeartMonitor,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconGasStationFilled,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconMessage,
  IconBrandGithub,
  IconCalendar,
  IconClock,
  IconReceipt2,
  IconReceipt,
  IconUsers,
  IconBuilding,
  IconBriefcase,
  IconRoad,
  IconCalendarDollar,
  IconAdjustmentsExclamation,
  IconBuildingMinus,
  IconFileArrowRight,
  IconFileUpload,
  IconBook,
  IconCalendarCheck,
  IconCalendarX,
  IconShield,
  IconPlane,
  IconEPassport,
  IconCoin,
  IconId,
  IconTruck,
  IconShirt,
  IconAdjustmentsDollar,
  IconCreditCardRefund,
  IconUserPlus,
  IconFoldersFilled,
  IconTool,
  IconShoppingCart,
  IconFlame,
  IconTemplate,
  IconBell
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  companies: IconBuilding,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  calendar: IconCalendar,
  clock: IconClock,
  receipt: IconReceipt,
  users: IconUsers,
  briefcase: IconBriefcase,
  expenseNote: IconReceipt2,
  mileageNote: IconRoad,
  calendarDollar:IconCalendarDollar,
  my_companies:IconBuildingMinus,
  import:IconFileUpload,
  actions:IconAdjustmentsExclamation,
  export:IconFileArrowRight,
  truck:IconTruck,
  fuel:IconGasStationFilled,
  message:IconMessage,
  book:IconBook,
  calendarcheck:IconCalendarCheck,
  calendarx:IconCalendarX,
  shield:IconShield,
  plane:IconPlane,
  passport:IconEPassport,
  currencyDollar:IconCoin,
  alertTriangle: IconAlertTriangle,
  id: IconId,
  shirt: IconShirt,
  fileText: IconFileText,
  consommation:IconAdjustmentsDollar,
  road:IconRoad,
  creditCard:IconCreditCardRefund,
  affectation:IconUserPlus,
  administratif:IconFoldersFilled,
  maintenance:IconTool,
  shoppingCart: IconShoppingCart,
  flame: IconFlame,
  template: IconTemplate,
  userDoctor: IconUserCircle,
  bell: IconBell,
  calendarDays: IconCalendar,
  fileHeart:IconDeviceHeartMonitor,
  stethoscope:IconStethoscope
};